INSERT IGNORE INTO reports (url, username) VALUES
('https://namesi\.kinsta\.cloud/wp\-content/plugins/dd/dd/pages/infromation\-page\.php', 'John Smith'),
('https://cassarottifoods\.com\.br/wp\-content/cache/tmp/Metamask/bec8986', 'John Smith'),
('http://wdfuygappwtr\.top', 'John Smith'),
('https://imsinc\.store/89041c13\-e59b\-4485\-a6f6\-89f228aafcdd/ULy8xokmroLtt1aA%5EKZ\~fyCLk2JjtWNsWR0GeZkn65PJaApVXuAu\*e%5ECw1aZHT9=AleDcmvqn7TO6Vnwtn5o=twIJdPJyDmcrL3A', 'John Smith'),
('https://ipfs\.io/ipfs/QmbEg8rd9V4hHUo9zCQtJVgxD3LD3vjyfoE8h9Ju6SJgcC', 'John Smith'),
('https://correosprepago\.bnext\.es/register', 'John Smith'),
('http://frouhasannojo\-5200\.vercel\.app/mixcc\.html', 'John Smith'),
('http://alfolw\.dk/\[email%C3%83%C2%82protected\]', 'John Smith'),
('http://www\.pb36566\.net', 'John Smith'),
('https://vtr466urd5ee64c5yr6d6u666\.weebly\.com', 'John Smith'),
('http://liechengsuwi\.anakembok\.de', 'John Smith'),
('http://jockeying\-authenticate\-freebies\.glitch\.me/temp/bin/8529cnb0q642hill73863\.html', 'John Smith'),
('http://rthrgr\.com', 'John Smith'),
('https://gerwzeqtr\.com/robots\.txt', 'John Smith'),
('https://br\.brasil105\-9070\.com\.br/\~fatur4927107', 'John Smith'),
('https://helpnets\.info/cfb7c55c5d86ac4872h96ef40cfo3c65f295\.htmlhttps/helpnets\.info/cfb7c55c5d86ac4872h96ef40cfo3c65f295\.html', 'John Smith'),
('https://yxc\.oau\.temporary\.site', 'John Smith'),
('http://ysncysqmji\.duckdns\.org/en/main', 'John Smith'),
('http://cancelencompraonline\.glitch\.me', 'John Smith'),
('http://mygov\-mediplus\.com', 'John Smith'),
('https://bafkreibdioyfesbsteb5kbe7dszvvewf7xeqnfpjc4jzyq75fpqaslfmbq\.ipfs\.flk\-ipfs\.xyz', 'John Smith'),
('https://wdvh7dxx\.skin', 'John Smith'),
('https://a1\.qpwunsajf\.com', 'John Smith'),
('https://www\.tobagency\.com', 'John Smith'),
('http://4852812coinbase\.com', 'John Smith'),
('http://trcsi0xgiczam5vmu7herxaxrpdqrnd\.drinksecrets\.shop/Oxo3RsCYzAJQiNMx4Keg4HRgB\+C7SZCS3Wg/aXzupmA8VziTCNl%201%20ioWYDR2GyC7yC%20\+%20g8b2XE/ZObmD3cen7LcA4MwiJ4gI%201%20iz5rocG4IP8Jp8Aka64/we\.php', 'John Smith'),
('https://b850\.asybc\.live', 'John Smith'),
('http://mecoreil\.com', 'John Smith'),
('https://codingbeats\.com/h', 'John Smith'),
('https://help\-zov\.xyz/i', 'John Smith'),
('https://www\.smvaeaa\.com', 'John Smith'),
('https://mailoptusnetcomau\.weebly\.com', 'John Smith'),
('https://epplae\.awsdykxgs\.co/aplee', 'John Smith'),
('https://qrco\.de/bfXdch', 'John Smith'),
('https://smartaikit\.shop', 'John Smith'),
('https://sanjinyneksa\.com', 'John Smith'),
('https://s\-games\.net/auth', 'John Smith'),
('https://portalkemaskinibantuansrt2024\.inf1\-id1\.com/4', 'John Smith'),
('https://portalkemaskinibantuansrt2024\.inf1\-id1\.com/ap', 'John Smith'),
('https://banttuan\-1bu\-bersallin\.get\-claim\.com', 'John Smith'),
('https://bantuan\-tunai\.inf1\-id1\.com/str1', 'John Smith'),
('https://iintro\-seegur\.site', 'John Smith'),
('https://nlo2wiluk\.top', 'John Smith'),
('https://zhhke2bwy\.top', 'John Smith'),
('https://clickwife\.com', 'John Smith'),
('https://idebar\.com', 'John Smith'),
('https://quixlink\.com', 'John Smith'),
('https://neoindo\.com', 'John Smith'),
('https://kurashi\.ncmncm\.com', 'John Smith'),
('https://suruga\-bank\.top', 'John Smith'),
('http://centrodeayuda\.glitch\.me', 'John Smith'),
('https://wa\-groupbebe\.pages\.dev', 'John Smith'),
('https://basescan\-snapshot0x28a5e71bfc02723eac17e39c84c5190415c0d9\.pages\.dev', 'John Smith'),
('https://mailoyinda\.weebly\.com', 'John Smith'),
('https://shaw\-105922\.weeblysite\.com', 'John Smith'),
('https://home\-102037\.weeblysite\.com', 'John Smith'),
('https://grammidafoida\.vercel\.app/ar\.html', 'John Smith'),
('https://round\-snowflake\-1bc1\.updatelogaccountprogramedrfwerwrdhsfetew\.workers\.dev', 'John Smith'),
('https://bjfedl\.com', 'John Smith'),
('https://bestorrogames\.com/landings/ro\-masha2/\?transaction_id=S3VSdnN5MG9xVys3b3cvSlhpRmFkZz09', 'John Smith'),
('https://purchasemanager\.thsite\.top/\?bread=3mail@b\.c', 'John Smith'),
('https://59560be5aca9c6316a3790bbd000ffc\.pages\.dev', 'John Smith'),
('https://inneterlandforyou\.hsater\.com', 'John Smith'),
('http://pibala\.com', 'John Smith'),
('https://qst\-fc7fa3\.ingress\-bonde\.ewp\.live/wp\-content/plugins/pajmch/pages/region\.php\?lca', 'John Smith'),
('https://dataarab89\.serv00\.net/Instagram/7823253465/index\.php', 'John Smith'),
('https://mahakaal08\.github\.io/Netflix', 'John Smith'),
('https://16734\.help/signin\?client_id=6729378b29475\-6729378b29477\-6729378b29478\-6729378b29479\&oauth_challenge=6729378b2947a\-6729378b2947b\-6729378b2947c\-6729378b2947d', 'John Smith'),
('https://bafybeiggrw4kkz5xjupszfsmwpytitphrqpmj4kjhu4ylgr6ubvcxksrci\.ipfs\.w3s\.link/never2\.htm\?hh', 'John Smith'),
('https://ethical\-shields\.com', 'John Smith'),
('https://kvanduk\.hu/ch', 'John Smith'),
('http://jj08ewhhh\.anakembok\.de', 'John Smith'),
('https://btinternet\-100857\.weeblysite\.com', 'John Smith'),
('https://albertanewsprint\.dogfriendlytahoe\.com', 'John Smith'),
('http://supportcaresecure\.weebly\.com', 'John Smith'),
('https://isdma\-portal\-apple\.com/signin\.html\?InvitationUrl=a9fe6fccb51b0676a9d93eebdfdf39c1\&KeyInvite=a9fe6fccb51b0676a9d93eebdfdf39c1', 'John Smith'),
('http://promobdvbanvanez\.servemp3\.com', 'John Smith'),
('https://gfk\.innodaclients\.com/scss/madrc/apps/CustomerService', 'John Smith'),
('http://helpnets\.info/ccf9d49ead88074a54h9dfc49c0o673cf425\.html', 'John Smith'),
('https://nycbikes\.com/cgibin', 'John Smith'),
('https://arched\-cabinet\-440317\-g8\.uw\.r\.appspot\.com/\#YWJ1c2VAaW9ub3MuY29', 'John Smith'),
('https://han\.gl/vLDob', 'John Smith'),
('https://jillyt\.sa\.com/fonts/rusr\.aruba/arubawebmail_myaccount\.aruba\.it', 'John Smith'),
('https://pznlre\.com/NED/NED1/n1/NedbankMoney\.htm', 'John Smith'),
('https://www\.ag\-strato\.com/apps', 'John Smith'),
('http://promerica\.top/a/card', 'John Smith'),
('https://margitmair3\.wixsite\.com/home', 'John Smith');

INSERT IGNORE INTO blocklist (url, approved_by) VALUES
('https://namesi\.kinsta\.cloud/wp\-content/plugins/dd/dd/pages/infromation\-page\.php', 1),
('https://cassarottifoods\.com\.br/wp\-content/cache/tmp/Metamask/bec8986', 1),
('http://wdfuygappwtr\.top', 1),
('https://imsinc\.store/89041c13\-e59b\-4485\-a6f6\-89f228aafcdd/ULy8xokmroLtt1aA%5EKZ\~fyCLk2JjtWNsWR0GeZkn65PJaApVXuAu\*e%5ECw1aZHT9=AleDcmvqn7TO6Vnwtn5o=twIJdPJyDmcrL3A', 1),
('https://ipfs\.io/ipfs/QmbEg8rd9V4hHUo9zCQtJVgxD3LD3vjyfoE8h9Ju6SJgcC', 1),
('https://correosprepago\.bnext\.es/register', 1),
('http://frouhasannojo\-5200\.vercel\.app/mixcc\.html', 1),
('http://alfolw\.dk/\[email%C3%83%C2%82protected\]', 1),
('http://www\.pb36566\.net', 1),
('https://vtr466urd5ee64c5yr6d6u666\.weebly\.com', 1),
('http://liechengsuwi\.anakembok\.de', 1),
('http://jockeying\-authenticate\-freebies\.glitch\.me/temp/bin/8529cnb0q642hill73863\.html', 1),
('http://rthrgr\.com', 1),
('https://gerwzeqtr\.com/robots\.txt', 1),
('https://br\.brasil105\-9070\.com\.br/\~fatur4927107', 1),
('https://helpnets\.info/cfb7c55c5d86ac4872h96ef40cfo3c65f295\.htmlhttps/helpnets\.info/cfb7c55c5d86ac4872h96ef40cfo3c65f295\.html', 1),
('https://yxc\.oau\.temporary\.site', 1),
('http://ysncysqmji\.duckdns\.org/en/main', 1),
('http://cancelencompraonline\.glitch\.me', 1),
('http://mygov\-mediplus\.com', 1),
('https://bafkreibdioyfesbsteb5kbe7dszvvewf7xeqnfpjc4jzyq75fpqaslfmbq\.ipfs\.flk\-ipfs\.xyz', 1),
('https://wdvh7dxx\.skin', 1),
('https://a1\.qpwunsajf\.com', 1),
('https://www\.tobagency\.com', 1),
('http://4852812coinbase\.com', 1),
('http://trcsi0xgiczam5vmu7herxaxrpdqrnd\.drinksecrets\.shop/Oxo3RsCYzAJQiNMx4Keg4HRgB\+C7SZCS3Wg/aXzupmA8VziTCNl%201%20ioWYDR2GyC7yC%20\+%20g8b2XE/ZObmD3cen7LcA4MwiJ4gI%201%20iz5rocG4IP8Jp8Aka64/we\.php', 1),
('https://b850\.asybc\.live', 1),
('http://mecoreil\.com', 1),
('https://codingbeats\.com/h', 1),
('https://help\-zov\.xyz/i', 1),
('https://www\.smvaeaa\.com', 1),
('https://mailoptusnetcomau\.weebly\.com', 1),
('https://epplae\.awsdykxgs\.co/aplee', 1),
('https://qrco\.de/bfXdch', 1),
('https://smartaikit\.shop', 1),
('https://sanjinyneksa\.com', 1),
('https://s\-games\.net/auth', 1),
('https://portalkemaskinibantuansrt2024\.inf1\-id1\.com/4', 1),
('https://portalkemaskinibantuansrt2024\.inf1\-id1\.com/ap', 1),
('https://banttuan\-1bu\-bersallin\.get\-claim\.com', 1),
('https://bantuan\-tunai\.inf1\-id1\.com/str1', 1),
('https://iintro\-seegur\.site', 1),
('https://nlo2wiluk\.top', 1),
('https://zhhke2bwy\.top', 1),
('https://clickwife\.com', 1),
('https://idebar\.com', 1),
('https://quixlink\.com', 1),
('https://neoindo\.com', 1),
('https://kurashi\.ncmncm\.com', 1),
('https://suruga\-bank\.top', 1),
('http://centrodeayuda\.glitch\.me', 1),
('https://wa\-groupbebe\.pages\.dev', 1),
('https://basescan\-snapshot0x28a5e71bfc02723eac17e39c84c5190415c0d9\.pages\.dev', 1),
('https://mailoyinda\.weebly\.com', 1),
('https://shaw\-105922\.weeblysite\.com', 1),
('https://home\-102037\.weeblysite\.com', 1),
('https://grammidafoida\.vercel\.app/ar\.html', 1),
('https://round\-snowflake\-1bc1\.updatelogaccountprogramedrfwerwrdhsfetew\.workers\.dev', 1),
('https://bjfedl\.com', 1),
('https://bestorrogames\.com/landings/ro\-masha2/\?transaction_id=S3VSdnN5MG9xVys3b3cvSlhpRmFkZz09', 1),
('https://purchasemanager\.thsite\.top/\?bread=3mail@b\.c', 1),
('https://59560be5aca9c6316a3790bbd000ffc\.pages\.dev', 1),
('https://inneterlandforyou\.hsater\.com', 1),
('http://pibala\.com', 1),
('https://qst\-fc7fa3\.ingress\-bonde\.ewp\.live/wp\-content/plugins/pajmch/pages/region\.php\?lca', 1),
('https://dataarab89\.serv00\.net/Instagram/7823253465/index\.php', 1),
('https://mahakaal08\.github\.io/Netflix', 1),
('https://16734\.help/signin\?client_id=6729378b29475\-6729378b29477\-6729378b29478\-6729378b29479\&oauth_challenge=6729378b2947a\-6729378b2947b\-6729378b2947c\-6729378b2947d', 1),
('https://bafybeiggrw4kkz5xjupszfsmwpytitphrqpmj4kjhu4ylgr6ubvcxksrci\.ipfs\.w3s\.link/never2\.htm\?hh', 1),
('https://ethical\-shields\.com', 1),
('https://kvanduk\.hu/ch', 1),
('http://jj08ewhhh\.anakembok\.de', 1),
('https://btinternet\-100857\.weeblysite\.com', 1),
('https://albertanewsprint\.dogfriendlytahoe\.com', 1),
('http://supportcaresecure\.weebly\.com', 1),
('https://isdma\-portal\-apple\.com/signin\.html\?InvitationUrl=a9fe6fccb51b0676a9d93eebdfdf39c1\&KeyInvite=a9fe6fccb51b0676a9d93eebdfdf39c1', 1),
('http://promobdvbanvanez\.servemp3\.com', 1),
('https://gfk\.innodaclients\.com/scss/madrc/apps/CustomerService', 1),
('http://helpnets\.info/ccf9d49ead88074a54h9dfc49c0o673cf425\.html', 1),
('https://nycbikes\.com/cgibin', 1),
('https://arched\-cabinet\-440317\-g8\.uw\.r\.appspot\.com/\#YWJ1c2VAaW9ub3MuY29', 1),
('https://han\.gl/vLDob', 1),
('https://jillyt\.sa\.com/fonts/rusr\.aruba/arubawebmail_myaccount\.aruba\.it', 1),
('https://pznlre\.com/NED/NED1/n1/NedbankMoney\.htm', 1),
('https://www\.ag\-strato\.com/apps', 1),
('http://promerica\.top/a/card', 1),
('https://margitmair3\.wixsite\.com/home', 1);


            UPDATE reports
            JOIN blocklist ON reports.url = blocklist.url
            SET reports.blocklist_website_id = blocklist.id;
        